### PR TITLE
Fix race condition on OffsetManager shutdown

### LINKED ISSUE #656: OffsetManager.Close() race condition
When closing OffsetManager, it can hang waiting for state to become "clean". 

The Close method uses AsyncClose internally. At L360, AsyncClose waits for a message on the ```clean``` chan before closing the ```dying``` chan:
```
		pom.lock.Lock()
		dirty := pom.dirty
		pom.lock.Unlock()

		if dirty {
			<-pom.clean
		}

		close(pom.dying)
```

However, ```updateCommitted``` can execute between ```AsyncClose()```'s ```pom.lock.Unlock()``` and receive on the ```clean``` chan:
```
	pom.lock.Lock()
	defer pom.lock.Unlock()
...
		select {
		case pom.clean <- none{}:
		default:
		}
```

The ```Close()``` method drains ```pom.errors``` at L371. This channel does not close until ```pom.dying``` is closed, which is selected in the mainLoop at L215

### PR DESCRIPTION
**Pull request by eapache**
If `updateCommitted` ran between the `Unlock` call and the read from `clean`
then we might miss the transition message and hang. Instead, use a condition
value from the `sync` package which does the right thing.

@wvanbergen @hasnickl fixes #656 

Supersedes #657

### CODE REVIEW

File: offset_manager.go [hunk 1]
```diff
@@ -353,11 +349,10 @@ func (pom *partitionOffsetManager) NextOffset() (int64, string) {
...
 	go func() {
 		pom.lock.Lock()
-		dirty := pom.dirty
-		pom.lock.Unlock()
+		defer pom.lock.Unlock()
 
-		if dirty {
-			<-pom.clean
+		for pom.dirty {
+			pom.clean.Wait()
```
Comment (hasnickl) [inline offset_manager.go]: I haven't seen ```sync.Cond``` used before. This looks like a pretty clean solution!

This seems to solve the issue with hanging, but could ```pom.dirty``` change to true after this goroutine finishes? I suppose this would only happen if ```MarkOffset``` is called after a ```Close```, is it worth worrying about?

**Comment by hasnickl** [comment]
lgtm

File: offset_manager.go (hunk 1 above)
Comment (eapache) [inline offset_manager.go]: calling anything after a `Close` or `AsyncClose` is user-error, not worth worrying about
