### PR TITLE
Instead of sleeping, poll for the socket to be ready

### LINKED ISSUE #399: Heisenbug
Finally managed to get a stack trace from kafka when creating topics in the test suite, this is the cause of our occasionally randomly failing tests:

```
Error while executing topic command org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
org.I0Itec.zkclient.exception.ZkNoNodeException: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
    at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:47)
    at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:685)
    at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:413)
    at org.I0Itec.zkclient.ZkClient.getChildren(ZkClient.java:409)
    at kafka.utils.ZkUtils$.getChildren(ZkUtils.scala:480)
    at kafka.utils.ZkUtils$.getSortedBrokerList(ZkUtils.scala:81)
    at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:154)
    at kafka.admin.TopicCommand$.createTopic(TopicCommand.scala:86)
    at kafka.admin.TopicCommand$.main(TopicCommand.scala:50)
    at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /brokers/ids
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
    at org.apache.zookeeper.KeeperException.create(KeeperException.java:42)
    at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1249)
    at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1277)
    at org.I0Itec.zkclient.ZkConnection.getChildren(ZkConnection.java:99)
    at org.I0Itec.zkclient.ZkClient$2.call(ZkClient.java:416)
    at org.I0Itec.zkclient.ZkClient$2.call(ZkClient.java:413)
    at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:675)
```

FWIW, this occurred on creating the first topic, while creating the second topic succeeded. I keep bumping the "wait for it to load" sleep call to no effect though, so I'm not sure what's going on.

### PR DESCRIPTION
**Pull request by eapache**
Hopefully this fixes the heisenbug where we try to set up the topics before the
cluster has actually booted.

Fixes #399 and shaves a good 20 seconds off of CI.

@Shopify/kafka

### CODE REVIEW

File: vagrant/boot_cluster.sh [hunk 1]
```diff
@@ -4,14 +4,15 @@ set -ex
 
 vagrant/run_toxiproxy.sh &
 
-sleep 5
+while ! nc -q 1 localhost 2181 </dev/null; do echo "Waiting"; sleep 1; done
```
Comment (yagnik) [inline vagrant/boot_cluster.sh]: til nc!

**Comment by yagnik** [comment]
:+1:

File: vagrant/boot_cluster.sh (hunk 1 above)
Comment (eapache) [inline vagrant/boot_cluster.sh]: There are a couple of different tools for doing something like this, but I had to try a couple until I found one that was available on travis *and* in the default vagrant box :)

**Comment by wvanbergen** [comment]
:+1:

I feel we should extract out the scripts to manage a ZK/Kafka cluster for CI purposes so we can more easily share them between projects. Not sure what the best way to approach that is.
